apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-backend
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: loki-backend
  template:
    metadata:
      labels:
        app: loki-backend
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.0
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secret
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: loki-s3-secret
                  key: secret_key
          volumeMounts:
            - name: config-vol
              mountPath: /etc/loki
      volumes:
        - name: config-vol
          secret:
            secretName: loki-s3-secret
